import { useEffect, useState } from "react";
import { useParams, Link } from "react-router-dom";
import { api } from "../api/client";
import type { AccountAnalysis } from "../api/types";
import AccountWorkspace from "../components/AccountWorkspace";
import ReportView from "../components/ReportView";
import SarModal from "../components/SarModal";

export default function Report() {
  const { id } = useParams();
  const [analysis, setAnalysis] = useState<AccountAnalysis | null>(null);
  const [notFound, setNotFound] = useState(false);
  const [sarOpen, setSarOpen] = useState(false);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    if (!id) return;
    api
      .getInvestigation(id)
      .then(setAnalysis)
      .catch(() =>
        api
          .getCase(id)
          .then((c) => (c.analysis ? setAnalysis(c.analysis) : setNotFound(true)))
          .catch(() => setNotFound(true))
      );
  }, [id]);

  if (notFound)
    return (
      <div className="panel p-8 text-textMuted">
        Case <span className="font-mono">{id}</span> not found.{" "}
        <Link to="/" className="text-accent hover:underline">
          Back to Operations Center
        </Link>
      </div>
    );
  if (!analysis) return <div className="text-textMuted">Loading report…</div>;

  const copyReport = () => {
    navigator.clipboard.writeText(analysis.ai_report);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  };

  return (
    <div>
      <header className="mb-6 flex items-center justify-between">
        <div>
          <h1 className="font-display text-[28px] font-bold text-primary">
            Operation Intelligence Report
          </h1>
          <p className="font-mono text-[13px] text-textSecondary">{analysis.case_id}</p>
        </div>
        <div className="flex gap-2">
          <button className="btn-ghost bg-white" onClick={copyReport}>
            {copied ? "Copied" : "Export Report Text"}
          </button>
          <button className="btn-primary" onClick={() => setSarOpen(true)}>
            Flag for SAR Review
          </button>
        </div>
      </header>

      <div className="flex flex-col gap-6">
        <AccountWorkspace a={analysis} />

        <div className="panel p-8">
          <ReportView report={analysis.ai_report} />
          <div className="mt-8 border-t border-border pt-4 text-[11px] font-mono text-textMuted">
            Generated by MULEFLAGGER Financial Intelligence Platform · BOI × IITH Hackathon 2026 · Model: XGBoost (
            {analysis.model_used}) · SHAP-attributed analysis · report source:{" "}
            {analysis.ai_report_source}
          </div>
        </div>
      </div>

      {sarOpen && <SarModal analysis={analysis} onClose={() => setSarOpen(false)} />}
    </div>
  );
}
